// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {installer} from '../models';

export function ApplyProcessingMode(arg1:installer.ProcessingModeRequest):Promise<installer.ProcessingModeApplyResult>;

export function ClaimDevice(arg1:installer.ClaimRequest):Promise<installer.ClaimResult>;

export function GetCurrentProcessingMode():Promise<installer.CurrentProcessingMode>;

export function GetInstallerState():Promise<installer.InstallerState>;

export function GetProcessingModeOptions():Promise<Array<installer.ProcessingModeOption>>;

export function GetSystemReport():Promise<installer.SystemReport>;

export function PlanProcessingMode(arg1:installer.ProcessingModeRequest):Promise<installer.ProcessingModePlan>;

export function ValidateProcessingMode(arg1:installer.ProcessingModeRequest):Promise<installer.ProcessingModeOption>;
