// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyProcessingMode(arg1) {
  return window['go']['main']['App']['ApplyProcessingMode'](arg1);
}

export function ClaimDevice(arg1) {
  return window['go']['main']['App']['ClaimDevice'](arg1);
}

export function GetCurrentProcessingMode() {
  return window['go']['main']['App']['GetCurrentProcessingMode']();
}

export function GetInstallerState() {
  return window['go']['main']['App']['GetInstallerState']();
}

export function GetProcessingModeOptions() {
  return window['go']['main']['App']['GetProcessingModeOptions']();
}

export function GetSystemReport() {
  return window['go']['main']['App']['GetSystemReport']();
}

export function PlanProcessingMode(arg1) {
  return window['go']['main']['App']['PlanProcessingMode'](arg1);
}

export function ValidateProcessingMode(arg1) {
  return window['go']['main']['App']['ValidateProcessingMode'](arg1);
}
