// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInstallerState() {
  return window['go']['main']['App']['GetInstallerState']();
}

export function GetSystemReport() {
  return window['go']['main']['App']['GetSystemReport']();
}
