// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {installer} from '../models';

export function ApplyCameraOnboarding(arg1:installer.CameraOnboardingRequest):Promise<installer.CameraOnboardingApplyResult>;

export function ApplyProcessingMode(arg1:installer.ProcessingModeRequest):Promise<installer.ProcessingModeApplyResult>;

export function CancelCameraOnboarding(arg1:number):Promise<void>;

export function ClaimDevice(arg1:installer.ClaimRequest):Promise<installer.ClaimResult>;

export function DiscoverCameras():Promise<installer.DiscoverCamerasResult>;

export function GetCurrentProcessingMode():Promise<installer.CurrentProcessingMode>;

export function GetDiscoveredCamera(arg1:string):Promise<installer.OnboardingCandidate>;

export function GetInstallerState():Promise<installer.InstallerState>;

export function GetProcessingModeOptions():Promise<Array<installer.ProcessingModeOption>>;

export function GetSystemReport():Promise<installer.SystemReport>;

export function PlanCameraOnboarding(arg1:installer.CameraOnboardingRequest):Promise<installer.CameraOnboardingPlan>;

export function PlanProcessingMode(arg1:installer.ProcessingModeRequest):Promise<installer.ProcessingModePlan>;

export function TestCameraCredentials(arg1:installer.TestCameraCredentialsRequest):Promise<installer.CameraValidationResult>;

export function ValidateProcessingMode(arg1:installer.ProcessingModeRequest):Promise<installer.ProcessingModeOption>;
