// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {installer} from '../models';

export function ClaimDevice(arg1:installer.ClaimRequest):Promise<installer.ClaimResult>;

export function GetInstallerState():Promise<installer.InstallerState>;

export function GetSystemReport():Promise<installer.SystemReport>;
