//go:build localbench

// Hito X's opt-in performance benchmarks. They are behind TWO gates on
// purpose:
//
//  1. the `localbench` build tag, so `go test ./...` never compiles or runs
//     them (the repository already uses this tag for Hito I10's local
//     bandwidth benchmark);
//  2. GEOCAM_PERF=1, so even `go test -tags localbench ./...` does not start a
//     multi-minute measurement by accident.
//
// Typical invocation (from the repository root):
//
//	GEOCAM_PERF=1 GEOCAM_PERF_OUT=/tmp/geocam-perf \
//	  GEOCAM_PERF_MODELS_DIR=/path/to/models \
//	  GEOCAM_PERF_PYTHON=/path/to/python3 \
//	  go test -tags localbench ./internal/perf/ -run 'TestXPerformance' -v -count=1
//
// The untagged tests in this package are what CI runs: they prove the harness
// compiles and its counters work, and they produce no performance number.
package perf

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"
)

func perfEnabled(t *testing.T) {
	t.Helper()
	if os.Getenv("GEOCAM_PERF") != "1" {
		t.Skip("performance benchmark is opt-in: set GEOCAM_PERF=1 (and build with -tags localbench) to run it")
	}
}

func envString(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func envInt(t *testing.T, key string, def int) int {
	t.Helper()
	raw := os.Getenv(key)
	if raw == "" {
		return def
	}
	n, err := strconv.Atoi(raw)
	if err != nil || n <= 0 {
		t.Fatalf("%s=%q is not a positive integer", key, raw)
	}
	return n
}

func envFloat(t *testing.T, key string, def float64) float64 {
	t.Helper()
	raw := os.Getenv(key)
	if raw == "" {
		return def
	}
	v, err := strconv.ParseFloat(raw, 64)
	if err != nil || v <= 0 {
		t.Fatalf("%s=%q is not a positive number", key, raw)
	}
	return v
}

// perfLogger returns a logger for the pipeline and vision worker. The default
// is silent: a benchmark's stderr is not part of its result. With
// GEOCAM_PERF_VERBOSE=1 the real structured logs go to stderr, which is how a
// surprising number (a decoder restart, a watchdog trip) is diagnosed instead
// of guessed at.
func perfLogger() *slog.Logger {
	if os.Getenv("GEOCAM_PERF_VERBOSE") == "1" {
		return slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))
	}
	return nil
}

func perfOutDir(t *testing.T) string {
	t.Helper()
	dir := os.Getenv("GEOCAM_PERF_OUT")
	if dir == "" {
		var err error
		dir, err = os.MkdirTemp("", "geocam-perf-out")
		if err != nil {
			t.Fatal(err)
		}
		t.Logf("GEOCAM_PERF_OUT not set: writing this run's artifacts to %s (set GEOCAM_PERF_OUT to keep them in a stable place)", dir)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	return dir
}

func sha256File(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:]), nil
}

// clipCache generates and verifies the video source once per process, so the
// decode and inference benchmarks cannot measure two different clips.
var (
	clipOnce sync.Once
	clipInfo ClipInfo
	clipAUs  []AccessUnit
	clipErr  error
)

// mustClip prepares the deterministic video source: either a pre-existing
// file (GEOCAM_PERF_CLIP_FILE) or one freshly generated by ffmpeg from
// GEOCAM_PERF_CLIP's spec, then independently verified with ffprobe.
//
// It regenerates the clip a second time to check the source is actually
// reproducible on this host, and records the answer instead of assuming it.
func mustClip(t *testing.T) (ClipInfo, []AccessUnit) {
	t.Helper()
	clipOnce.Do(func() {
		ctx := context.Background()
		ffmpeg := envString("GEOCAM_PERF_FFMPEG", "ffmpeg")
		ffprobe := envString("GEOCAM_PERF_FFPROBE", "ffprobe")
		spec, err := ParseClipSpec(os.Getenv("GEOCAM_PERF_CLIP"))
		if err != nil {
			clipErr = err
			return
		}
		outDir := os.Getenv("GEOCAM_PERF_OUT")

		if file := os.Getenv("GEOCAM_PERF_CLIP_FILE"); file != "" {
			clipInfo, clipAUs, clipErr = ClipInfo{
				Path:                   file,
				Container:              "raw H.264 Annex-B elementary stream (pre-existing file)",
				Codec:                  "h264",
				Width:                  spec.Width,
				Height:                 spec.Height,
				NominalSourceFPS:       spec.FPS,
				NominalSourceFPSSource: fmt.Sprintf("configured spec: nominal_source_fps=%g cannot be derived from a raw Annex-B file", spec.FPS),
				GenerationCommand:      "(pre-existing clip via GEOCAM_PERF_CLIP_FILE, not generated by this harness)",
			}.VerifyAndParse(ctx, ffprobe)
			return
		}

		dir := outDir
		if dir == "" {
			dir, err = os.MkdirTemp("", "geocam-perf-clip")
			if err != nil {
				clipErr = err
				return
			}
		}
		primary := filepath.Join(dir, "hito-x-clip.h264")
		regen := filepath.Join(dir, "hito-x-clip-regen.h264")

		clipInfo, err = GenerateClip(ctx, ffmpeg, spec, primary)
		if err != nil {
			clipErr = err
			return
		}
		// Determinism check: same spec, same host, byte-identical output.
		second, err := GenerateClip(ctx, ffmpeg, spec, regen)
		if err != nil {
			clipErr = err
			return
		}
		clipInfo.RegeneratedIdentical = second.SHA256 == clipInfo.SHA256

		clipInfo, clipAUs, clipErr = clipInfo.VerifyAndParse(ctx, ffprobe)
	})
	if clipErr != nil {
		t.Fatalf("preparing the video source: %v", clipErr)
	}
	return clipInfo, clipAUs
}

func writeReport(t *testing.T, report Report, name string) string {
	t.Helper()
	path := filepath.Join(perfOutDir(t), name)
	if err := report.WriteJSON(path); err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
	t.Logf("wrote %s", path)
	var buf strings.Builder
	report.Summary(&buf)
	t.Log("\n" + buf.String())
	return path
}

// TestXPerformanceDecode measures video decode FPS on the real pipeline.
func TestXPerformanceDecode(t *testing.T) {
	perfEnabled(t)
	if os.Getenv("GEOCAM_PERF_INFER_ONLY") == "1" {
		t.Skip("GEOCAM_PERF_INFER_ONLY=1")
	}
	ctx := context.Background()
	clip, aus := mustClip(t)
	t.Logf("video source: codec=%s profile=%s %dx%d nominal_fps=%g coded_frames=%d sha256=%s boundary=%s regenerated_identical=%t",
		clip.Codec, clip.Profile, clip.Width, clip.Height, clip.NominalSourceFPS, clip.CodedFrames, clip.SHA256, clip.AccessUnitBoundary, clip.RegeneratedIdentical)
	if !clip.RegeneratedIdentical {
		t.Logf("WARNING: the clip is not bit-reproducible on this host; it is still a valid, fully described source, but two runs are not byte-identical")
	}
	sps, pps := ParameterSets(aus)

	base := DecodeOptions{
		Clip:         clip,
		AUs:          aus,
		SPS:          sps,
		PPS:          pps,
		FFmpegPath:   envString("GEOCAM_PERF_FFMPEG", "ffmpeg"),
		OutputWidth:  clip.Width,
		OutputHeight: clip.Height,
		SampleFPS:    envFloat(t, "GEOCAM_PERF_SAMPLE_FPS", 5),
		Stability:    time.Duration(envInt(t, "GEOCAM_PERF_STABILITY_MS", 750)) * time.Millisecond,
		Timeout:      3 * time.Minute,
	}

	base.Logger = perfLogger()
	if os.Getenv("GEOCAM_PERF_TRACE") == "1" {
		base.TraceInterval = 250 * time.Millisecond
	}
	selected := map[string]bool{}
	for _, name := range strings.Split(envString("GEOCAM_PERF_DECODE_RUNS", "realtime,realtime3x,max,direct"), ",") {
		selected[strings.TrimSpace(name)] = true
	}

	type decodeRun struct {
		name, label string
		opts        DecodeOptions
	}
	all := []decodeRun{
		{"realtime", "production pipeline, real-time pacing", withModePacingKeep(base, DecodeModePipeline, PacingRealtime, PacingMultiplierRealtime, envInt(t, "GEOCAM_PERF_KEEP_FRAMES", 48))},
		{"realtime3x", "production pipeline, 3x real-time pacing (sustained-headroom probe)", withModePacingKeep(base, DecodeModePipeline, PacingRealtime, PacingMultiplierThreeX, 0)},
		{"max", "production pipeline, maximum pacing (burst, not a sustained ceiling)", withModePacingKeep(base, DecodeModePipeline, PacingMax, 0, 0)},
		{"direct", "decoder driven directly, maximum pacing", withModePacingKeep(base, DecodeModeDirect, PacingMax, 0, 0)},
		{"direct-realtime", "decoder driven directly, real-time pacing", withModePacingKeep(base, DecodeModeDirect, PacingRealtime, PacingMultiplierRealtime, 0)},
	}
	var runs []decodeRun
	for _, r := range all {
		if selected[r.name] {
			runs = append(runs, r)
		}
	}

	results := make([]DecodeResult, 0, len(runs))
	for _, r := range runs {
		t.Logf("running: %s", r.label)
		res, err := RunDecode(ctx, r.opts)
		if err != nil {
			t.Fatalf("%s: %v", r.label, err)
		}
		if len(res.Errors) > 0 {
			t.Logf("  errors: %v", res.Errors)
		}
		t.Logf("  fed=%d (priming=%d measured=%d) decoded=%d sampled=%d dropped=%d lag=%d",
			res.FramesFed, res.PrimingFrames, res.MeasuredFrames, res.FramesDecoded, res.FramesSampled, res.FramesDropped, res.BufferedLagFrames)
		t.Logf("  pacing_fps=%.2f priming=%.1fms ttff=%.1fms send=%.1fms feed=%.1fms ingest_fps=%.2f decode_fps=%.2f sampled_fps=%.2f steady=%t (decode/ingest=%.3f)",
			res.PacingFPS, res.PrimingMS, res.TimeToFirstFrameMS, res.SendElapsedMS, res.FeedElapsedMS, res.IngestFPS, res.DecodeFPS, res.SampleFPS,
			res.SteadyStateAchieved, res.DecodeToIngestRatio)
		t.Logf("  tail_flushed=%d tail_flush=%.1fms decode_fps_end_to_end=%.2f delivery=%.4f errors=%v",
			res.TailFramesFlushed, res.TailFlushMS, res.DecodeFPSEndToEnd, res.TransportDeliveryRatio, res.Errors)
		results = append(results, res)
	}

	host := ProbeHost(ctx, hostPython())
	report := Report{
		SchemaVersion: SchemaVersion,
		Kind:          "decode",
		GeneratedAt:   time.Now().UTC(),
		Harness:       "internal/perf (go test -tags localbench ./internal/perf -run TestXPerformanceDecode)",
		Host:          host,
		Clip:          &clip,
		Decode:        results,
		Environment:   CaptureEnvironment(),
		Limitations: []string{
			"the video source is a synthetic lavfi testsrc2 clip generated by this harness, not real camera footage; it is fully described above and byte-reproducible on this host",
			"the RTSP transport is loopback TCP to internal/rtsptest.Simulator, so there is no Wi-Fi/LTE loss, jitter or retransmission delay",
			"one camera only: this is not a 1/5/10/25/50-camera capacity measurement",
			"the ffmpeg build used is the benchmark host's, which is not necessarily the LGPL-only build shipped in the appliance image",
		},
	}
	writeReport(t, report, "hito-x-decode.json")
}

// TestXPerformanceInference measures inference FPS through the real Python
// vision worker and the real YOLO weights.
func TestXPerformanceInference(t *testing.T) {
	perfEnabled(t)
	if os.Getenv("GEOCAM_PERF_DECODE_ONLY") == "1" {
		t.Skip("GEOCAM_PERF_DECODE_ONLY=1")
	}
	ctx := context.Background()

	python := hostPython()
	script := envString("GEOCAM_PERF_WORKER_SCRIPT", filepath.Join("..", "..", "deploy", "vision-worker", "worker.py"))
	if _, err := os.Stat(script); err != nil {
		t.Fatalf("vision worker script %s not found: %v", script, err)
	}
	modelsDir := os.Getenv("GEOCAM_PERF_MODELS_DIR")
	if modelsDir == "" {
		t.Fatalf("real inference needs model weights: set GEOCAM_PERF_MODELS_DIR to a directory containing yolo11s-pose.pt and yolo11n.pt (the harness never downloads a model)")
	}

	samples := envInt(t, "GEOCAM_PERF_INFER_SAMPLES", 50)
	warmup := envInt(t, "GEOCAM_PERF_INFER_WARMUP", 3)

	// Real decoded frames from the real pipeline, so the worker sees the
	// content a camera would produce rather than a synthetic buffer.
	var (
		clip                    ClipInfo
		frames                  [][]byte
		frameWidth, frameHeight int
	)
	clip, aus := mustClip(t)
	sps, pps := ParameterSets(aus)
	dec, err := RunDecode(ctx, DecodeOptions{
		Mode:         DecodeModePipeline,
		Clip:         clip,
		AUs:          aus,
		SPS:          sps,
		PPS:          pps,
		Pacing:       PacingRealtime,
		FFmpegPath:   envString("GEOCAM_PERF_FFMPEG", "ffmpeg"),
		OutputWidth:  clip.Width,
		OutputHeight: clip.Height,
		SampleFPS:    envFloat(t, "GEOCAM_PERF_SAMPLE_FPS", 5),
		Timeout:      3 * time.Minute,
		KeepFrames:   samples,
	})
	if err != nil {
		t.Fatalf("decode pass for inference frames: %v", err)
	}
	frames = dec.Collected.Frames
	frameWidth, frameHeight = dec.Collected.Width, dec.Collected.Height
	t.Logf("inference frames: %d decoded frames at %dx%d from the real pipeline (decode_fps=%.2f)", len(frames), frameWidth, frameHeight, dec.DecodeFPS)
	if len(frames) == 0 {
		t.Fatalf("the pipeline produced no sampled frames to run inference on")
	}

	device := envString("GEOCAM_PERF_DEVICE", "cpu")
	res, err := RunInference(ctx, InferenceOptions{
		WorkerCmd:         python,
		WorkerArgs:        []string{script},
		Kind:              WorkerRealYOLO,
		ModelsDir:         modelsDir,
		PersonModel:       "yolo11s-pose.pt",
		VehicleModel:      "yolo11n.pt",
		Device:            device,
		ImgSize:           envInt(t, "GEOCAM_PERF_IMGSZ", 640),
		PersonConfidence:  0.5,
		VehicleConfidence: 0.5,
		NMSIoU:            0.45,
		SocketPath:        tempSocketPath(),
		Warmup:            warmup,
		Samples:           samples,
		YUV:               frames,
		YUVWidth:          frameWidth,
		YUVHeight:         frameHeight,
		FrameSourceLabel:  fmt.Sprintf("real pipeline-decoded frames (%dx%d, sampled at %g fps)", frameWidth, frameHeight, envFloat(t, "GEOCAM_PERF_SAMPLE_FPS", 5)),
		PythonPath:        python,
	})
	if err != nil {
		t.Fatalf("RunInference: %v", err)
	}
	t.Logf("inference: real=%t device=%s (requested %s) worker_infer_p50=%.2fms sink_route_p50=%.2fms worker_fps=%.2f edge_fps=%.2f errors=%d",
		res.Real, res.DeviceEffective, res.DeviceRequested, res.WorkerInferenceMS.P50MS, res.SinkRouteMS.P50MS,
		res.WorkerInferenceFPS, res.SinkRouteFPS, res.InferenceErrors)

	host := ProbeHost(ctx, python)
	report := Report{
		SchemaVersion: SchemaVersion,
		Kind:          "inference",
		GeneratedAt:   time.Now().UTC(),
		Harness:       "internal/perf (go test -tags localbench ./internal/perf -run TestXPerformanceInference)",
		Host:          host,
		Clip:          &clip,
		Inference:     &res,
		Environment:   CaptureEnvironment(),
		Limitations: []string{
			"the frames fed to the worker come from a synthetic testsrc2 clip, not from a real camera",
			"this measures the model on the benchmark host; it is not a claim about the appliance's CPU, and CPU numbers must never be extrapolated to a GPU (or the reverse)",
		},
	}
	writeReport(t, report, "hito-x-inference.json")
}

// hostPython resolves the interpreter used both for the host's torch probe
// and, by default, to run the vision worker.
func hostPython() string {
	if p := os.Getenv("GEOCAM_PERF_PYTHON"); p != "" {
		return p
	}
	return LookPath("python3")
}

// withModePacingKeep builds one run, deriving the priming pre-roll from the
// pacing: real-time runs reproduce a camera and need it, maximum-pacing runs
// measure a ceiling and must not have it.
func withModePacingKeep(base DecodeOptions, mode DecodeMode, pacing Pacing, multiplier float64, keep int) DecodeOptions {
	base.Mode = mode
	base.Pacing = pacing
	base.PacingMultiplier = multiplier
	base.KeepFrames = keep
	base.PrimingFrames = DefaultPrimingFrames(base.Clip, len(base.AUs), pacing, multiplier)
	return base
}
